services:
  # 1. The PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:z
    networks:
      - nexus-network
    ports:
    - "5173:5173"

  # 2. The Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nexus_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nexus-network

  # 3. The Database
  db:
    image: mysql:8.0
    container_name: nexus_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - nexus-network

  # 4. Vite / Node (Optional - helps with HMR)
  # We will just run npm run dev inside the 'app' container, 
  # but we need to open the port here.
  
networks:
  nexus-network:
    driver: bridge

volumes:
  dbdata: